import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Suspense } from "react";
import AuthGuard from "@/components/shared/AuthGuard";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-gray-50`}
      >
        <Suspense fallback={null}>
          <Header />
        </Suspense>
        <AuthGuard>
          <main className="flex-1 container mx-auto p-4 flex flex-col">
            {children}
          </main>
        </AuthGuard>
        <Toaster />
        {/* <Script id="vapi-ai-init" strategy="afterInteractive">
          {`
            var vapiInstance = null;
            const assistant = "4e33fffe-7a27-4a4e-a4f6-cae8ad6668eb"; 
            const apiKey = "8aff7b94-0a49-4909-8831-69876a7f7e24"; 
            const buttonConfig = {}; 
            (function (d, t) {
                var g = document.createElement(t),
                s = d.getElementsByTagName(t)[0];
                g.src =
                "https://cdn.jsdelivr.net/gh/VapiAI/html-script-tag@latest/dist/assets/index.js";
                g.defer = true;
                g.async = true;
                s.parentNode.insertBefore(g, s);
                g.onload = function () {
                vapiInstance = window.vapiSDK.run({
                    apiKey: apiKey,
                    assistant: assistant,
                    config: buttonConfig,
                });
                };
            })(document, "script");
          `}
        </Script> */}
      </body>
    </html>
  );
}
